name: Python package on FreeBSD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: '3.10'
            py: '310'
          - python-version: '3.11'
            py: '311'
          - python-version: '3.12'
            py: '312'
          - python-version: '3.13'
            py: '313'
          - python-version: '3.14'
            py: '314'
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'
    - name: Run FreeBSD CI
      uses: vmactions/freebsd-vm@v1
      with:
        release: '15.1'
        usesh: true
        prepare: |
          pkg install -y rust git python3 py312-uv cups graphviz
          pkg install -y python${{ matrix.py }} py${{ matrix.py }}-sqlite3
        run: |
          uname -o
          python3 --version
          echo "-- Syncing python version --"
          uv python pin ${{ matrix.python-version }}
          uv sync
          echo "-- Installing CI/CD dependencies --"
          uv pip install --python ${{ matrix.python-version }} flake8 pytest tox tox-gh
          if [ -f requirements.txt ]; then uv pip install --python ${{ matrix.python-version }} -r requirements.txt; fi
          echo "-- Export environment variables --"
          export CPPFLAGS="-I/usr/local/include"
          export ESCPOS_CAPABILITIES_FILE="/home/runner/work/python-escpos/python-escpos/capabilities-data/dist/capabilities.json"
          echo "-- Test with tox --"
          uv run --python ${{ matrix.python-version }} tox --conf pyproject.toml
          echo "-- Run examples --"
          uv run --python ${{ matrix.python-version }} examples/receipt.py
          uv run --python ${{ matrix.python-version }} examples/font_variations.py
          uv run --python ${{ matrix.python-version }} examples/block_text.py
