# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
        py: ['310']
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'
    - name: Run FreeBSD CI
      uses: vmactions/freebsd-vm@v1
      env:
        ESCPOS_CAPABILITIES_FILE: /home/runner/work/python-escpos/python-escpos/capabilities-data/dist/capabilities.json
      with:
        release: "15.0"
        usesh: true
        prepare: |
          pkg install -y git python3 py312-uv cups graphviz enchant
          pkg install -y python${{ matrix.py }}
        #   export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}
        run: |
          uname -o
          python3 --version
          # cargo install --locked uv
          # export PATH="$PATH:/root/.cargo/bin"
          echo "-- Syncing python version --"
          uv python pin ${{ matrix.python-version }}
          uv sync
          echo "-- Installing CI/CD dependencies --"
          uv pip install --python ${{ matrix.python-version }} flake8 pytest tox tox-gh
          if [ -f requirements.txt ]; then uv pip install --python ${{ matrix.python-version }} -r requirements.txt; fi
      # env:
      #   PATH: $PATH:/root/.cargo/bin
      # #   CPPFLAGS: -I/usr/local/include
    # - name: Install tox on FreeBSD
    #   run: |
    #     git clone https://github.com/tox/pyproject.git
    #     cd tox/pyproject
    #     pip install -e .
    # - name: Test with tox
    #   run: |
    #     tox --conf pyproject.toml
    #   env:
    #     ESCPOS_CAPABILITIES_FILE: /home/runner/work/python-escpos/python-escpos/capabilities-data/dist/capabilities.json
